image: node

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm install
    - npm run generate

pages:
  stage: deploy
  script:
    - rm -rf public
    - mkdir public && cp -rf dist/* public
  artifacts:
    paths:
      - public

cache:
  paths:
    - node_modules
    - dist
